"""add subcategories

Revision ID: 29d9c695568b
Revises: 8c7a7a1e6a5c
Create Date: 2023-11-25 13:06:23.696538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d9c695568b'
down_revision: Union[str, None] = '8c7a7a1e6a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('sub_category_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_category_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'sub_categories', ['sub_category_id'], ['id'])
    op.drop_column('transactions', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_category_id_fkey', 'transactions', 'categories', ['category_id'], ['id'])
    op.drop_column('transactions', 'sub_category_id')
    op.drop_table('sub_categories')
    # ### end Alembic commands ###
