"""Update category

Revision ID: 81b031bdf5d3
Revises: 5ed4e8ca5c69
Create Date: 2023-11-27 08:46:58.135136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b031bdf5d3'
down_revision: Union[str, None] = '5ed4e8ca5c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_categories', 'title',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_categories', 'title',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
