"""update transaction

Revision ID: f272feb771bc
Revises: 89eb0225c00a
Create Date: 2023-11-25 09:38:47.217277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f272feb771bc'
down_revision: Union[str, None] = '89eb0225c00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('updated_date_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated_date_time')
    # ### end Alembic commands ###
